server:
  port: 9001
spring:
  application:
    name: tensquare-base
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.101:3306/tensquare_base?chracterEncoding=utf-8&useSSL=true
    username: root
    password: 123456
  jpa:
    database: mysql
    show-sql: true
  rabbitmq:
    host: 192.168.139.128
eureka:
  client:
    service-url:
      defaultZone: http://192.168.139.128:6868/eureka/
  instance:
    prefer-ip-address: true #支持跨域访问
